name: checkbox_grouped
on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+*'
permissions:
  id-token: write # This is required for requesting the JWT
  contents: write  # This is required for actions/checkout

jobs:
  publish:
    runs-on: ubuntu-latest
    container:
      image:  python:3
    steps:
      - uses: actions/checkout@v3
      - name: export tag
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - uses: dart-lang/setup-dart@v1
      - name: Install Flutter SDK
        uses: britannio/action-install-flutter@v1
      - run: dart --version
      - run: flutter --version
      - name: fomarting files
        run : dart format .
      - name: Publish package
        run: flutter pub publish -f

      - name: release version
        uses: ncipollo/release-action@v1
        with:
            tag: ${{ env.RELEASE_VERSION }}
            name: ${{ env.RELEASE_VERSION }}
            token: ${{ secrets.GITHUB_TOKEN }}